### ISSUE TITLE
UDFPS for kebab

### ISSUE THREAD

**Issue by bojantanasic** [PixelExtended/Fan-Edition_Settings#48]
UDFPS icon picker not working
UDFPS animation effect not working
App lock not working

**Comment by GioKas93** [comment]
For UDFPS have you set up correctly the required overlays in DT?
For applock try to provide a log of the error bro.. Without it's very hard to sort out things

**Comment by bojantanasic** [comment]
I don't have App lock in settings so it's not possible to provide log for that
I'm using DT from pixel expiriance and I didn't set up overlays, i will setup and try.
Thank you very much:)

**Comment by GioKas93** [comment]
For app lock try under Security --> More settings security

**Comment by ralf979** [comment]
Before opening an issue,
make sure you set everything in your DT
if you use the DT of other ROMs everything doesn't work if you don't adapt the DT to the rom you want to build.
then closed, and if you need help building the rom join the telegram group
https://t.me/pixelextended
